export const CAMPAIGN_CONSTANTS = {
  TITLE: "crm.campaign.title",
  LIST_TITLE: "crm.campaignsList",
  CREATE_TITLE: "crm.campaign.title",
  DESCRIPTION_TITLE: "common.createDescription",
  EDIT_TITLE: "crm.campaign",
  DESCRIPTION_EDIT: "common.editDescription",
  SEARCH_PLACEHOLDER: "common.filter",
  CONFIRM_DELETE: "common.delete",
  RECORD_NOT_FOUND: "common.recordNotFound",
  END_OF_RECORDS: "common.endOfRecords",
  ACTIONS: "crm.campaign.actions",
  GENERAL_CAMPAIGNS: "crm.campaign.general",
  CUSTOM_CAMPAIGNS: "crm.campaign.custom",
  COLUMNS: {
    CODE: "crm.campaign.columns.code",
    NAME: "crm.campaign.columns.name",
    STATUS: "common.status",
    DATES: "crm.campaign.columns.dates",
  },
  FORM: {
    CODE: "common.code",
    NAME: "crm.campaign.name",
    FROM_DATE: "crm.fromDate",
    TO_DATE: "crm.toDate",
    CURRENCY_CODE: "common.currency",
    DEFAULT_SPREAD_PERCENT: "common.spreadPercent",
    STATUS: "common.status",
    PRIORITY: "common.priority",
    CUSTOMER: "common.customer",
    SUBMIT: "common.save",
    CANCEL: "common.cancel",
    DIRTY_WARNING: "common.dirty_warning",
    CONFIRM_CANCEL: "common.confirmCancel",
    YES_DISCARD: "common.yesDiscard",
    NO_STAY: "common.noStay",
    FORM_STATUS: "common.formStatus",
    FORM_MODIFIED: "common.formModified",
    FORM_WARNING: "common.formWarning",
    SELECT_OPTION: "common.selectOption"
  },
  ROUTES: {
    BACK: -1,
    CAMPAIGN: "/crm/commercial/campaign/custom",
    CAMPAIGN_NEW: "/crm/commercial/campaign/custom/new",
  },
  VIEW_DETAIL: "common.viewDetail",
  EDIT_RECORD: "common.editRecord",
  VIEW_PRODUCTS: "crm.campaign.viewProducts"
};
