export const INVITATION_CONSTANTS = {
  TITLE: "crm.invitation.title",
  LIST_TITLE: "crm.invitation.listTitle",
  CREATE_TITLE: "crm.invitation.createTitle",
  EDIT_TITLE: "crm.invitation.editTitle",
  DESCRIPTION_TITLE: "crm.invitation.descriptionTitle",
  DESCRIPTION_EDIT: "crm.invitation.descriptionEdit",
  SEARCH_PLACEHOLDER: "crm.invitation.searchPlaceholder",
  VIEW_DETAIL: "crm.invitation.viewDetail",
  EDIT_RECORD: "crm.invitation.editRecord",
  CONFIRM_DELETE: "crm.invitation.confirmDelete",
  END_OF_RECORDS: "crm.invitation.endOfRecords",
  NEW_INVITATION: "crm.invitation.new",
  FORM: {
    TO: "crm.invitation.to",
    SUBJECT: "crm.invitation.subject",
    BODY: "crm.invitation.body",
    URL: "crm.invitation.url",
    FROM_DATE: "crm.invitation.fromDate",
    TO_DATE: "crm.invitation.toDate",
    PROFILES: "crm.invitation.profiles",
    SUBMIT: "common.save",
    CANCEL: "common.cancel",
    FORM_STATUS: "common.formStatus",
    FORM_MODIFIED: "common.formModified",
    FORM_WARNING: "crm.invitation.formWarning",
    CONFIRM_CANCEL: "common.confirmCancel",
    DIRTY_WARNING: "common.dirtyWarning",
    YES_DISCARD: "common.yesDiscard",
    NO_STAY: "common.noStay",
    SELECT_OPTION: "common.selectOption",
  },
  COLUMNS: {
    TO: "crm.invitation.to",
    SUBJECT: "crm.invitation.subject",
    STATUS: "common.status",
    CREATED_AT: "common.createdAt",
  },
  ROUTES: {
    BACK: -1,
    INVITATION: "/crm/person/invitation",
    INVITATION_NEW: "/crm/person/invitation/new",
  }
};
