export const COMMERCIAL_PRODUCT_CONSTANTS = {
  TITLE: "crm.commercialProduct.title",
  LIST_TITLE: "crm.commercialProductsList",
  CREATE_TITLE: "crm.commercialProduct",
  DESCRIPTION_TITLE: "common.createDescription",
  EDIT_TITLE: "crm.commercialProduct",
  DESCRIPTION_EDIT: "common.editDescription",
  SEARCH_PLACEHOLDER: "common.filter",
  CONFIRM_DELETE: "common.delete",
  RECORD_NOT_FOUND: "common.recordNotFound",
  END_OF_RECORDS: "common.endOfRecords",
  ACTIONS: "commercial.campaign.actions",
  COLUMNS: {
    CODE: "commercial.campaign.columns.code",
    NAME: "commercial.campaign.columns.name",
    STATUS: "commercial.campaign.columns.status",
    DATES: "commercial.campaign.columns.dates",
  },
  FORM: {
    CODE: "commercial.code",
    NAME: "commercial.name",
    FROM_DATE: "commercial.fromDate",
    TO_DATE: "commercial.toDate",
    CURRENCY_CODE: "commercial.currencyCode",
    DEFAULT_SPREAD_PERCENT: "commercial.defaultSpreadPercent",
    STATUS: "commercial.status",
    PRIORITY: "commercial.priority",
    PERSON_ID: "commercial.personId",
    SUBMIT: "common.save",
    CANCEL: "common.cancel",
    DIRTY_WARNING: "common.dirty_warning",
    CONFIRM_CANCEL: "common.confirmCancel",
    YES_DISCARD: "common.yesDiscard",
    NO_STAY: "common.noStay",
    FORM_STATUS: "common.formStatus",
    FORM_MODIFIED: "common.formModified",
    FORM_WARNING: "common.formWarning",
    SELECT_OPTION: "common.selectOption"
  },
  ROUTES: {
    BACK: -1,
    COMMERCIAL_PRODUCT: "/crm/commercial/commercial-product",
    COMMERCIAL_PRODUCT_NEW: "/crm/commercial/commercial-product/new",
  },
  VIEW_DETAIL: "common.viewDetail",
  EDIT_RECORD: "common.editRecord"
};
