export const COMMERCIAL_PRODUCT_CONSTANTS = {
  TITLE: "crm.commercialProduct.title",
  LIST_TITLE: "crm.commercialProductsList",
  CREATE_TITLE: "crm.commercialProduct.create",
  DESCRIPTION_TITLE: "crm.commercialProduct.createDescription",
  EDIT_TITLE: "crm.commercialProduct.edit",
  DESCRIPTION_EDIT: "crm.commercialProduct.editDescription",
  SEARCH_PLACEHOLDER: "common.filter",
  CONFIRM_DELETE: "common.delete",
  RECORD_NOT_FOUND: "common.recordNotFound",
  END_OF_RECORDS: "common.endOfRecords",
  ACTIONS: "common.actions",
  COLUMNS: {
    CODE: "common.code",
    NAME: "common.name",
    STATUS: "common.status",
    PRICE_TYPE: "crm.commercialProduct.priceType",
    TOTAL_COST: "crm.commercialProduct.totalCost",
  },
  FORM: {
    CODE: "common.code",
    NAME: "crm.commercialProduct.name",
    DESCRIPTION: "common.description",
    PRICE_TYPE: "crm.commercialProduct.priceType",
    TOTAL_COST: "crm.commercialProduct.totalCost",
    ATTENTION_GROUP: "crm.commercialProduct.attentionGroup",
    CHANNEL: "crm.commercialProduct.channel",
    STATUS: "common.status",
    TYPE: "common.type",
    UNIQUE_PRODUCT: "crm.commercialProduct.uniqueProduct",
    COMBO: "crm.commercialProduct.combo",
    BASE_PRODUCT: "common.product",
    COST: "crm.commercialProduct.cost",
    QUANTITY: "crm.commercialProduct.quantity",
    UNIT_MEASURE: "crm.commercialProduct.unitMeasure",
    CONFIGURATION_CODE: "crm.commercialProduct.configurationCode",
    SUBMIT: "common.save",
    CANCEL: "common.cancel",
    DIRTY_WARNING: "common.dirty_warning",
    CONFIRM_CANCEL: "common.confirmCancel",
    YES_DISCARD: "common.yesDiscard",
    NO_STAY: "common.noStay",
    FORM_STATUS: "common.formStatus",
    FORM_MODIFIED: "common.formModified",
    SELECT_OPTION: "common.selectOption"
  },
  VALIDATION: {
    CAMPAIGN_REQUIRED: "crm.commercialProduct.validation.campaignRequired",
    CODE_REQUIRED: "crm.commercialProduct.validation.codeRequired",
    NAME_REQUIRED: "crm.commercialProduct.validation.nameRequired",
    PRICE_TYPE_REQUIRED: "crm.commercialProduct.validation.priceTypeRequired",
    ATTENTION_GROUP_REQUIRED: "crm.commercialProduct.validation.attentionGroupRequired",
    CHANNEL_REQUIRED: "crm.commercialProduct.validation.channelRequired",
    STATUS_REQUIRED: "crm.commercialProduct.validation.statusRequired",
    BASE_PRODUCT_REQUIRED: "crm.commercialProduct.validation.baseProductRequired",
    COST_REQUIRED: "crm.commercialProduct.validation.costRequired",
    QUANTITY_REQUIRED: "crm.commercialProduct.validation.quantityRequired",
    UNIT_MEASURE_REQUIRED: "crm.commercialProduct.validation.unitMeasureRequired",
    CONFIG_CODE_REQUIRED: "crm.commercialProduct.validation.configCodeRequired",
  },
  ROUTES: {
    BACK: -1,
    COMMERCIAL_PRODUCT: "/crm/commercial/commercial-product",
  },
  EDIT_RECORD: "common.editRecord"
};
