export const WAREHOUSE_CONSTANTS = {
  TITLE: "warehouse.title",
  LIST_TITLE: "warehouse.listTitle",
  CREATE_TITLE: "warehouse.createTitle",
  EDIT_TITLE: "warehouse.editTitle",
  DESCRIPTION_TITLE: "warehouse.createDescription",
  DESCRIPTION_EDIT: "warehouse.editDescription",
  SEARCH_PLACEHOLDER: "warehouse.searchPlaceholder",
  CONFIRM_DELETE: "common.delete",
  RECORD_NOT_FOUND: "common.recordNotFound",
  END_OF_RECORDS: "common.endOfRecords",
  ACTIONS: "common.actions",
  COLUMNS: {
    CODE: "warehouse.columns.code",
    NAME: "warehouse.columns.name",
    TYPE: "warehouse.columns.type",
    LOCATION: "warehouse.columns.location",
    COST_METHOD: "warehouse.columns.costMethod",
    STATUS: "warehouse.columns.status",
    CREATED: "warehouse.columns.created",
  },
  FORM: {
    CODE: "warehouse.form.code",
    NAME: "warehouse.form.name",
    TYPE: "warehouse.form.type",
    LOCATION_CODE: "warehouse.form.locationCode",
    ADDRESS: "warehouse.form.address",
    COST_METHOD_CODE: "warehouse.form.costMethodCode",
    STATUS: "warehouse.form.status",
    SUBMIT: "common.save",
    CANCEL: "common.cancel",
    DIRTY_WARNING: "common.dirty_warning",
    CONFIRM_CANCEL: "common.confirmCancel",
    YES_DISCARD: "common.yesDiscard",
    NO_STAY: "common.noStay",
    FORM_STATUS: "common.formStatus",
    FORM_MODIFIED: "common.formModified",
    FORM_WARNING: "common.formWarning",
    SELECT_OPTION: "common.selectOption"
  },
  ROUTES: {
    BACK: -1,
    WAREHOUSE: "/warehouse/warehouse",
    WAREHOUSE_NEW: "/warehouse/warehouse/new",
  },
  VIEW_DETAIL: "common.viewDetail",
  EDIT_RECORD: "common.editRecord"
};
