export const ORGANIZATION_CONSTANTS = {
  LIST_TITLE: "crm.organization.listTitle",
  CREATE_TITLE: "crm.organization.listTitle",
  EDIT_TITLE: "crm.organization.listTitle",
  DESCRIPTION_TITLE: "crm.organization.descriptionTitle",
  DESCRIPTION_EDIT: "common.editRecord",
  SEARCH_PLACEHOLDER: "crm.organization.searchPlaceholder",
  RECORD_NOT_FOUND: "crm.organization.record_not_found",
  CONFIRM_DELETE: "crm.organization.confirm_delete",
  TREE_TITLE: "crm.organization.listTitle",
  HIERARCHY_VIEW: "crm.organizationHierarchy",
  LOADING_STRUCTURE: "common.loading",
  EDIT_NODE: "common.editNode",
  NEW_NODE: "common.newNode",
  ADD_ROOT: "common.addRoot",
  VIEW_ORGANZATIONS: "crm.organization.view",
  YES: "common.yes",
  NO: "common.no",
  ROUTES: {
    ORGANIZATION: "/crm/organization",
  },
  FORM: {
    CODE: "common.code",
    NAME: "common.name",
    ADDRESS: "common.address",
    PARENT_ORG: "crm.organization.parentOrg",
    MAX_ATTENTION: "crm.organization.maxAttention",
    TICKET_METHOD: "crm.organization.ticketMethod",
    TICKET_COUNTER: "crm.organization.ticketCounter",
    TYPE: "common.type",
    SUBMIT: "common.save",
    CANCEL: "common.cancel",
    DIRTY_WARNING: "common.dirty_warning",
    SELECT_OPTION: "common.selectOption",
  }
};
