export const PERSON_DIGITAL_CONTENT_CONSTANTS = {
  TITLE: "crm.personDigitalContent",
  LIST_TITLE: "crm.personDigitalContentsList",
  CREATE_TITLE: "crm.personDigitalContent",
  DESCRIPTION_TITLE: "common.createDescription",
  EDIT_TITLE: "crm.personDigitalContent",
  DESCRIPTION_EDIT: "common.editDescription",
  SEARCH_PLACEHOLDER: "common.filter",
  CONFIRM_DELETE: "common.confirmDelete",
  RECORD_NOT_FOUND: "common.recordNotFound",
  FORM: {
    TYPE: "crm.mediaType",
    CODE: "crm.digitalContentCode",
    PRIORITY: "common.priority",
    SUBMIT: "common.save",
    CANCEL: "common.cancel",
    DIRTY_WARNING: "common.dirty_warning",
    FILE: "common.files",
    SELECT_OPTION: "common.selectOption",
    CONFIRM_CANCEL: "common.confirmCancel",
    YES_DISCARD: "common.yesDiscard",
    NO_STAY: "common.noStay",
    UPLOAD_LABEL: "common.uploadClick",
    UPLOAD_HINT: "common.uploadHint",
    REMOVE_FILE: "common.uploadRemoveFile",
  },
  MODULE_CODE: "CRM",
  ENTITY_NAME: "PersonDigitalContent",
  BUCKET_NAME: "crm",
  ROUTES: {
    BACK: -1,
    PERSON_DIGITAL_CONTENT: "/crm/person-digital-content",
    PERSON_DIGITAL_CONTENT_NEW: "/crm/person-digital-content/new",
  }
};
