export const WORK_EXPERIENCE_CONSTANTS = {
  TITLE: "crm.workExperience",
  LIST_TITLE: "crm.workExperiencesList",
  CREATE_TITLE: "crm.workExperience",
  DESCRIPTION_TITLE: "common.createDescription",
  EDIT_TITLE: "crm.workExperience",
  DESCRIPTION_EDIT: "common.editDescription",
  SEARCH_PLACEHOLDER: "common.filter",
  CONFIRM_DELETE: "common.confirmDelete",
  RECORD_NOT_FOUND: "common.recordNotFound",
  FORM: {
    NAME: "crm.companyName",
    POSITION: "crm.position",
    DESCRIPTION: "crm.workDescription",
    FROM_DATE: "crm.fromDate",
    TO_DATE: "crm.toDate",
    SUBMIT: "common.save",
    CANCEL: "common.cancel",
    DIRTY_WARNING: "common.dirty_warning",
    SELECT_OPTION: "common.selectOption",
    CONFIRM_CANCEL: "common.confirmCancel",
    YES_DISCARD: "common.yesDiscard",
    NO_STAY: "common.noStay",
    EX_NAME: "crm.workExperienceCompanyPlaceholder",
    EX_DESCRIPTION: "crm.workExperienceDescriptionPlaceholder",
  },
  ROUTES: {
    BACK: -1,
    WORK_EXPERIENCE: "/crm/work-experience",
    WORK_EXPERIENCE_NEW: "/crm/work-experience/new",
  }
};
