export const COMMUNICATION_CHANNEL_CONSTANTS = {
  TITLE: "common.communicationChannel",
  LIST_TITLE: "common.communicationChannelsList",
  CREATE_TITLE: "common.communicationChannel",
  DESCRIPTION_TITLE: "common.createDescription",
  EDIT_TITLE: "crm.communicationChannel",
  DESCRIPTION_EDIT: "common.editDescription",
  SEARCH_PLACEHOLDER: "common.filter",
  CONFIRM_DELETE: "common.confirmDelete",
  RECORD_NOT_FOUND: "common.recordNotFound",
  FORM: {
    TYPE: "crm.communicationChannelType",
    DATA: "crm.communicationChannelData",
    KIND: "crm.communicationChannelKind",
    PRIORITY: "common.priority",
    EX_DATA: "crm.communicationChannelDataPlaceholder",
    SUBMIT: "common.save",
    CANCEL: "common.cancel",
    DIRTY_WARNING: "common.dirty_warning",
    SELECT_OPTION: "common.selectOption",
    CONFIRM_CANCEL: "common.confirmCancel",
    YES_DISCARD: "common.yesDiscard",
    NO_STAY: "common.noStay",
  },
  ROUTES: {
    BACK: -1,
    COMMUNICATION_CHANNEL: "/crm/communication-channel",
    COMMUNICATION_CHANNEL_NEW: "/crm/communication-channel/new",
  }
};
