export const SCHEDULE_CONSTANTS = {
  TITLE: "crm.schedule.title",
  LIST_TITLE: "crm.schedule.title",
  CREATE_TITLE: "crm.schedule.appointment",
  DESCRIPTION_TITLE: "common.createDescription",
  EDIT_TITLE: "crm.commercialSchedule",
  DESCRIPTION_EDIT: "common.editDescription",
  SEARCH_PLACEHOLDER: "common.filter",
  CONFIRM_DELETE: "common.delete",
  RECORD_NOT_FOUND: "common.recordNotFound",
  END_OF_RECORDS: "common.endOfRecords",
  ACTIONS: "crm.campaign.actions",
  VIEW_SCHEDULE: "crm.schedule.view",
  AGENDA_SUBTITLE: "crm.schedule.agendaSubtitle",
  TIME_HEADER: "crm.schedule.time",
  NO_PRODUCT_ID: "crm.schedule.noProductId",
  GO_BACK: "common.back",
  COLUMNS: {
    CODE: "crm.campaign.columns.code",
    NAME: "crm.campaign.columns.name",
    STATUS: "crm.campaign.columns.status",
    DATES: "crm.campaign.columns.dates",
  },
  DAYS: {
    MON: "common.monday",
    TUE: "common.tuesday",
    WED: "common.wednesday",
    THU: "common.thursday",
    FRI: "common.friday",
    SAT: "common.saturday",
    SUN: "common.sunday",
  },
  FORM: {
    DAY: "common.day",
    FROM_TIME: "common.fromTime",
    TO_TIME: "common.toTime",
    QUANTITY: "common.quantity",
    UNIT_MEASURE: "common.unitMeasure",
    STATUS: "common.status",
    COLLABORATOR: "common.collaborator",
    ORGANIZATION: "common.attentionPoint",
    SUBMIT: "common.save",
    CANCEL: "common.cancel",
    DIRTY_WARNING: "common.dirty_warning",
    CONFIRM_CANCEL: "common.confirmCancel",
    YES_DISCARD: "common.yesDiscard",
    NO_STAY: "common.noStay",
    FORM_STATUS: "common.formStatus",
    FORM_MODIFIED: "common.formModified",
    FORM_WARNING: "common.formWarning",
    SELECT_OPTION: "common.selectOption"
  },
  ROUTES: {
    BACK: -1,
    SCHEDULE: "/crm/commercial/schedule",
    SCHEDULE_NEW: "/crm/commercial/schedule/new"
  },
  VIEW_DETAIL: "common.viewDetail",
  EDIT_RECORD: "common.editRecord"
};
